mergerfs 2.38.0

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# shellcheck disable=SC2086,SC2181
+
+
 if [[ $(id -u) -ne 0 ]]; then
   echo "This script must be executed as root or using sudo."
   exit 99
@@ -10,8 +13,10 @@ declare -i version
 url="https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/"
 
 version=$(dpkg -l openmediavault | awk '$2 == "openmediavault" { print substr($3,1,1) }')
+echo "OMV ${version}"
 
-echo ${version}
+codename="$(lsb_release --codename --short)"
+echo "Codename :: ${codename}"
 
 if [ ${version} -lt 5 ]; then
   echo "Unsupported version of openmediavault"
@@ -26,11 +31,24 @@ fi
 echo "Downloading omv-extras.org plugin for openmediavault ${version}.x ..."
 file="openmediavault-omvextrasorg_latest_all${version}.deb"
 
+if ! grep -qrE "^deb.*${codename}\s+main" /etc/apt/sources.list*; then
+  echo "Adding missing main repo..."
+  echo "deb http://deb.debian.org/debian/ ${codename} main contrib non-free" | tee -a /etc/apt/sources.list
+fi
+if ! grep -qrE "^deb.*${codename}-updates\s+main" /etc/apt/sources.list*; then
+  echo "Adding missing main updates repo..."
+  echo "deb http://deb.debian.org/debian/ ${codename}-updates main contrib non-free" | tee -a /etc/apt/sources.list
+fi
+
 echo "Updating repos before installing..."
 apt-get update
 
 echo "Install prerequisites..."
 apt-get --yes --no-install-recommends install gnupg
+if [ $? -gt 0 ]; then
+  echo "Unable to install prerequisites.  Exiting."
+  exit 10
+fi
 
 if [ -f "${file}" ]; then
   rm ${file}
